experiment_name: t5_xsum_pretrain
random_seed: 42
raw_data_path: xsum
output_dir: t5_xsum
processed_dir: t5_xsum/data/processed
raw_dir: t5_xsum/data/raw
model_name: t5-base
max_length: 256
block_size: 256
batch_size: 8
epochs: 1
learning_rate: 0.0003
mixed_precision: true
val_size: 2000
strategy: auto
log_dir: t5_xsum/logs
ckpt_dir: t5_xsum/logs/checkpoints
save_interval: 1000
use_wandb: true
run_name: t5_xsum-seq2seq
noise_density: 0.15
mean_span_length: 3
